name: nutrimate
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  async_redux: ^23.0.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Bold.ttf
        - asset: fonts/Urbanist-ExtraBold.ttf
        - asset: fonts/Urbanist-ExtraLight.ttf
        - asset: fonts/Urbanist-Light.ttf
        - asset: fonts/Urbanist-Medium.ttf
        - asset: fonts/Urbanist-Regular.ttf
        - asset: fonts/Urbanist-SemiBold.ttf
        - asset: fonts/Urbanist-Thin.ttf
