name: nutrimate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Bold.ttf
        - asset: fonts/Urbanist-ExtraBold.ttf
        - asset: fonts/Urbanist-ExtraLight.ttf
        - asset: fonts/Urbanist-Light.ttf
        - asset: fonts/Urbanist-Medium.ttf
        - asset: fonts/Urbanist-Regular.ttf
        - asset: fonts/Urbanist-SemiBold.ttf
        - asset: fonts/Urbanist-Thin.ttf
