import 'package:flutter/material.dart';
import 'package:nutrimate/domain/core/value_objects/app_strings.dart';
import 'package:nutrimate/presentation/core/theme/theme.dart';
import 'package:nutrimate/presentation/core/widgets/custom_app_bar.dart';
import 'package:nutrimate/presentation/global/spaces.dart';
import 'package:nutrimate/presentation/global/text_themes.dart';

class TermsAndConditionsPage extends StatelessWidget {
  const TermsAndConditionsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: PreferredSize(
        preferredSize: const Size.fromHeight(60),
        child: CustomAppBar(
          showBackButton: true,
          onBackButtonPressed: () => Navigator.pop(context),
          title: termsAndConditionString,
        ),
      ),
      body: Padding(
        padding: const EdgeInsets.all(20),
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              mediumVerticalSizedBox,
              Text(
                'Disclaimer',
                style: boldSize20Text(
                  AppColors.blackColor,
                ),
              ),
              smallVerticalSizedBox,
              Text(
                'Data Privacy',
                style: boldSize15Text(
                  AppColors.blackColor,
                ),
              ),
              mediumVerticalSizedBox,
              Text(
                'We take your privacy very seriously. Any data you provide will be securely stored and used solely for the purpose of enhancing your experience and providing personalized nutrition recommendations. We do not share your data with third parties without your explicit consent.',
                style: normalSize14Text(
                  AppColors.blackColor,
                ),
              ),
              largeVerticalSizedBox,
              Text(
                'Accuracy of Information',
                style: boldSize15Text(
                  AppColors.blackColor,
                ),
              ),
              mediumVerticalSizedBox,
              Text(
                'While we strive to provide accurate and up-to-date nutritional advice, the recommendations generated by this chatbot are based on available data and algorithms. These recommendations should not replace professional medical advice. Always consult a healthcare provider or a registered dietitian for personalized advice.',
                style: normalSize14Text(
                  AppColors.blackColor,
                ),
              ),
              largeVerticalSizedBox,
              Text(
                'Limitation of Results',
                style: boldSize15Text(
                  AppColors.blackColor,
                ),
              ),
              mediumVerticalSizedBox,
              Text(
                'There may be instances where the chatbot cannot provide a precise answer to your query due to the limitations of our current database or the complexity of your question. We apologize for any inconvenience this may cause and are continuously working to improve our system.',
                style: normalSize14Text(
                  AppColors.blackColor,
                ),
              ),
              largeVerticalSizedBox,
              Text(
                'Terms and Conditions',
                style: boldSize20Text(
                  AppColors.blackColor,
                ),
              ),
              smallVerticalSizedBox,
              Text(
                'Acceptance of Terms',
                style: boldSize15Text(
                  AppColors.blackColor,
                ),
              ),
              mediumVerticalSizedBox,
              Text(
                'By using our Nutrition Recommendation System, you agree to comply with and be bound by these terms and conditions. If you do not agree with these terms, please do not use the service.',
                style: normalSize14Text(
                  AppColors.blackColor,
                ),
              ),
              largeVerticalSizedBox,
              Text(
                'Use of Service',
                style: boldSize15Text(
                  AppColors.blackColor,
                ),
              ),
              mediumVerticalSizedBox,
              Text(
                'The service is intended for personal use to provide general nutritional advice. Commercial use or misuse of the service is prohibited.',
                style: normalSize14Text(
                  AppColors.blackColor,
                ),
              ),
              largeVerticalSizedBox,
              Text(
                'Data Usage',
                style: boldSize15Text(
                  AppColors.blackColor,
                ),
              ),
              mediumVerticalSizedBox,
              Text(
                'Your data will be used as outlined in our privacy policy. You consent to the collection, use, and storage of your data as described.',
                style: normalSize14Text(
                  AppColors.blackColor,
                ),
              ),
              largeVerticalSizedBox,
              Text(
                'No Professional Advice',
                style: boldSize15Text(
                  AppColors.blackColor,
                ),
              ),
              mediumVerticalSizedBox,
              Text(
                'The information provided by the chatbot is for general informational purposes only and does not constitute professional advice. Always seek the advice of a qualified healthcare provider for any medical or nutritional concerns.',
                style: normalSize14Text(
                  AppColors.blackColor,
                ),
              ),
              largeVerticalSizedBox,
              Text(
                'Limitation of Liability',
                style: boldSize15Text(
                  AppColors.blackColor,
                ),
              ),
              mediumVerticalSizedBox,
              Text(
                'We are not liable for any inaccuracies or omissions in the information provided or for any actions you take based on the information received from the chatbot.',
                style: normalSize14Text(
                  AppColors.blackColor,
                ),
              ),
              largeVerticalSizedBox,
              Text(
                'Changes to Terms',
                style: boldSize15Text(
                  AppColors.blackColor,
                ),
              ),
              mediumVerticalSizedBox,
              Text(
                'We reserve the right to modify these terms and conditions at any time. Your continued use of the service constitutes acceptance of any changes.',
                style: normalSize14Text(
                  AppColors.blackColor,
                ),
              ),
              largeVerticalSizedBox,
              Text(
                'Termination',
                style: boldSize15Text(
                  AppColors.blackColor,
                ),
              ),
              mediumVerticalSizedBox,
              Text(
                'We reserve the right to terminate or restrict your access to the service for any reason, including violation of these terms and conditions.',
                style: normalSize14Text(
                  AppColors.blackColor,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
